# -*- coding: utf-8 -*-
"""turtle_bot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/ggolrym/43760dff602889a5456a333df1b1ce68/turtle_bot-py.ipynb
"""

import os
import yfinance as yf
import FinanceDataReader as fdr
import google.generativeai as genai
import requests
import time
from datetime import datetime

# 1. 금고에서 비밀번호 꺼내오기
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
DISCORD_WEBHOOK_URL = os.environ.get("DISCORD_WEBHOOK_URL")

MARKET = "KOSPI" # 한국 주식
TEST_COUNT = 0 # 0이면 전체 주식 검사 (수백 개라 시간이 좀 걸려요!)

print("🤖 슈퍼 터틀 로봇 가동 시작!\n")

genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel('gemini-1.5-flash')

market_info = fdr.StockListing(MARKET)
stock_list = market_info['Symbol'].tolist()
stock_names = market_info['Name'].tolist()

if TEST_COUNT > 0:
    stock_list = stock_list[:TEST_COUNT]
    stock_names = stock_names[:TEST_COUNT]

buy_signals = []
sell_signals = []

# 2. 전체 주식 하나씩 검사하기
for i in range(len(stock_list)):
    ticker = stock_list[i]
    name = stock_names[i]

    try:
        yahoo_ticker = ticker + '.KS' if MARKET == "KOSPI" else ticker

        # 200일 평균을 구하기 위해 1년 치 데이터 가져오기
        stock_data = yf.download(yahoo_ticker, period='1y', progress=False)

        if len(stock_data) >= 200:
            recent_20_high = stock_data['High'].iloc[-20:].max().item()
            ma_200 = stock_data['Close'].rolling(window=200).mean().iloc[-1].item()
            today_volume = stock_data['Volume'].iloc[-1].item()
            recent_10_low = stock_data['Low'].iloc[-10:].min().item()
            current_price = stock_data['Close'].iloc[-1].item()

            # 🟢 [매수 조건] 20일 최고가 돌파 + 200일선 돌파 + 거래량 10만 이상!
            if (current_price >= recent_20_high) and (current_price > ma_200) and (today_volume >= 100000):
                buy_signals.append(name)
                print(f"🚀 [발견!] {name}")

            # 🔴 [매도 조건] 10일 최저가 붕괴
            elif current_price <= recent_10_low:
                sell_signals.append(name)

    except Exception as e:
        pass

    time.sleep(0.5) # 에러 안 나게 0.5초씩 천천히

# 3. 제미나이에게 보고서 쓰라고 시키기
if len(buy_signals) > 0 or len(sell_signals) > 0:
    prompt = f"""
    너는 12살도 이해하기 쉽게 설명해주는 최고의 주식 비서야.
    오늘 한국 시간으로 {datetime.now().strftime('%Y년 %m월 %d일')}이야.

    - 🟢 매수 추천 (200일선 뚫고 거래량 10만 터진 슈퍼 주식!): {buy_signals if buy_signals else '없음'}
    - 🔴 매도 경고 (10일 최저가 깨져서 도망쳐야 할 주식): {sell_signals if sell_signals else '없음'}

    이 결과를 바탕으로 디스코드 알림 메시지를 작성해줘. 이모티콘 듬뿍 넣어서!
    """

    response = model.generate_content(prompt)

    # 4. 디스코드로 메시지 전송!
    message_data = {"content": f"🐢 **슈퍼 터틀 로봇 브리핑** 🐢\n{response.text}"}
    requests.post(DISCORD_WEBHOOK_URL, data=message_data)
